export const FETCH_HERO_DETAIL_SUCCESS = 'FETCH_HERO_DETAIL_SUCCESS';
export const FETCH_HERO_DETAIL_ERROR = 'FETCH_HERO_DETAIL_ERROR';
export const FETCH_HERO_COMICS_SUCCESS = 'FETCH_HERO_COMICS_SUCCESS';
export const FETCH_HERO_COMICS_ERROR = 'FETCH_HERO_COMICS_ERROR';